# ---------- STEP 1: Use Flutter with Dart 3.8 ----------
FROM ghcr.io/cirruslabs/flutter:3.32.5 AS build

# Set working directory
WORKDIR /app

# Copy Flutter project
COPY . .

# Get dependencies and build web
RUN flutter pub get
RUN flutter build web

# ---------- STEP 2: Serve using NGINX ----------
FROM nginx:alpine

# Clear default content
RUN rm -rf /usr/share/nginx/html/*

# Copy web build to nginx html folder
COPY --from=build /app/build/web /usr/share/nginx/html

# Expose web server port
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]
